CC = g++ -I.  -pthread
CFLAGS = -c -pedantic -ansi -Wall -g


#-lDS -L./mostUpdatedDS/DS/

timeOps.o: timeOps.cpp timeOps.h
	$(CC) $(CFLAGS) timeOps.cpp
	

	
	
clean:
	rm -rf timeOps.o
	rm -f timeOps
	
